monolog:
    channels: [ blueMediaApi, blueMediaFinalizeTransaction, blueMediaWebhook ]
    handlers:
        blueMediaApi:
            type: rotating_file
            path: "%kernel.logs_dir%/blue-media/blue-media-shopware-payment.api.%kernel.environment%.log"
            level: debug
            max_files: 14
            formatter: 'monolog.formatter.json'
            channels: [ blueMediaApi ]
        blueMediaFinalizeTransaction:
            type: rotating_file
            path: "%kernel.logs_dir%/blue-media/blue-media-shopware-payment.finalize-transaction.%kernel.environment%.log"
            level: debug
            max_files: 14
            formatter: 'monolog.formatter.json'
            channels: [ blueMediaFinalizeTransaction ]
        blueMediaWebhook:
            type: rotating_file
            path: "%kernel.logs_dir%/blue-media/blue-media-shopware-payment.webhook.%kernel.environment%.log"
            level: debug
            max_files: 14
            formatter: 'monolog.formatter.json'
            channels: [ blueMediaWebhook ]