imports:
  - { resource: monolog.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    BlueMedia\ShopwarePayment\PaymentHandler\BlueMediaPaymentHandlerInterface:
      tags: ['blue_media.shopware_payment.payment_handler']

  # MAIN NAMESPACE
  BlueMedia\ShopwarePayment\:
    resource: '../../'

  # LIFECYCLE
  BlueMedia\ShopwarePayment\Lifecycle\ActivateDeactivate:
    public: true
    arguments:
        $payments: [
          '@BlueMedia\ShopwarePayment\Lifecycle\Payments\GeneralBlueMediaPayment',
          '@BlueMedia\ShopwarePayment\Lifecycle\Payments\DetailedBlueMediaPayment',
          '@BlueMedia\ShopwarePayment\Lifecycle\Payments\PayByLinkPayment',
          '@BlueMedia\ShopwarePayment\Lifecycle\Payments\QuickTransferPayment',
          '@BlueMedia\ShopwarePayment\Lifecycle\Payments\ApplePayPayment',
          '@BlueMedia\ShopwarePayment\Lifecycle\Payments\CardPayment',
          '@BlueMedia\ShopwarePayment\Lifecycle\Payments\BlikPayment',
          '@BlueMedia\ShopwarePayment\Lifecycle\Payments\GooglePayPayment'
        ]

  BlueMedia\ShopwarePayment\Lifecycle\Rules\RulesManager:
    public: true

  BlueMedia\ShopwarePayment\Lifecycle\Icons\ProxyMediaService:
    public: true

  # API
  BlueMedia\ShopwarePayment\Api\Client:
    factory: [ '@BlueMedia\ShopwarePayment\Api\ClientFactory', 'createFromPluginConfig' ]

  BlueMedia\ShopwarePayment\Api\ClientFactory:
    arguments:
      $shopwareVersion: '%kernel.shopware_version%'

  # CART DATA COLLECTORS
  BlueMedia\ShopwarePayment\Cart\GatewayListDataCollector:
    tags: [ 'shopware.cart.collector' ]

  # CART VALIDATORS
  BlueMedia\ShopwarePayment\Validator\IntegrationEnabledCartValidator:
    tags: ['shopware.cart.validator']

  BlueMedia\ShopwarePayment\Validator\GatewaySelectedCartValidator:
    tags: ['shopware.cart.validator']

  # DEFINITIONS
  BlueMedia\ShopwarePayment\Entity\Gateway\GatewayDefinition:
    tags: [ 'shopware.entity.definition' ]

  BlueMedia\ShopwarePayment\Entity\GatewayCurrency\GatewayCurrencyDefinition:
    tags: [ 'shopware.entity.definition' ]

  BlueMedia\ShopwarePayment\Entity\Gateway\Aggregate\GatewaySalesChannelsActiveDefinition:
    tags: [ 'shopware.entity.definition' ]

  BlueMedia\ShopwarePayment\Entity\Gateway\Aggregate\GatewaySalesChannelsEnabledDefinition:
    tags: [ 'shopware.entity.definition' ]

  # EVENT SUBSCRIBERS
  BlueMedia\ShopwarePayment\Subscriber\OrderTransactionStateChangeEventListener:
    tags: [ 'kernel.event_subscriber' ]

  # PAYMENT HANDLERS
  BlueMedia\ShopwarePayment\PaymentHandler\GeneralPaymentHandler:
    tags: [ 'shopware.payment.method.async' ]

  BlueMedia\ShopwarePayment\PaymentHandler\DetailedPaymentHandler:
    tags: [ 'shopware.payment.method.async' ]

  BlueMedia\ShopwarePayment\PaymentHandler\ApplePayPaymentHandler:
    tags: [ 'shopware.payment.method.async' ]

  BlueMedia\ShopwarePayment\PaymentHandler\PayByLinkPaymentHandler:
    tags: [ 'shopware.payment.method.async' ]

  BlueMedia\ShopwarePayment\PaymentHandler\BlikPaymentHandler:
    tags: [ 'shopware.payment.method.async' ]

  BlueMedia\ShopwarePayment\PaymentHandler\GooglePayPaymentHandler:
    tags: [ 'shopware.payment.method.async' ]

  BlueMedia\ShopwarePayment\PaymentHandler\QuickTransferPaymentHandler:
    tags: [ 'shopware.payment.method.sync' ]

  BlueMedia\ShopwarePayment\PaymentHandler\CardPaymentHandler:
    tags: [ 'shopware.payment.method.sync' ]

  # RESOLVERS
  BlueMedia\ShopwarePayment\Resolver\PaymentHandlerResolver:
    arguments:
      - !tagged_iterator { tag: 'blue_media.shopware_payment.payment_handler' }

  # RULES
  BlueMedia\ShopwarePayment\Rule\BlueMediaGatewayAvailable:
    tags: ['shopware.rule.definition']

  # TASKS
  BlueMedia\ShopwarePayment\ScheduledTask\GatewaySynchronizationTask:
    tags: [ 'shopware.scheduled.task' ]

  # TWIG EXTENSIONS
  BlueMedia\ShopwarePayment\Twig\ApplePayTwigExtension:
    tags: [ 'twig.extension' ]

  BlueMedia\ShopwarePayment\Twig\GatewayListTwigExtension:
    tags: [ 'twig.extension' ]

  BlueMedia\ShopwarePayment\Twig\QuickTransferTwigExtension:
    tags: [ 'twig.extension' ]

  BlueMedia\ShopwarePayment\Twig\CardTwigExtension:
    tags: [ 'twig.extension' ]

  BlueMedia\ShopwarePayment\Twig\GooglePayTwigExtension:
    tags: [ 'twig.extension' ]